import type { ImageLoaderProps } from "next/image";
import manifest from "../public/assets/optimized/manifest.json";
import { OPTIMIZED_DIR } from "./image-config.mjs";

type ManifestEntry = {
  hash: string;
  widths: number[];
  blurDataURL: string;
};

type Manifest = Record<string, ManifestEntry>;

const IMAGE_MANIFEST = manifest as Manifest;
const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

function slugify(src: string): string {
  const file = src.split("/").pop() ?? src;
  return file.replace(/\.[^./]+$/, "");
}

/** Smallest generated width that's still >= the requested width; falls back
 * to the largest generated width when the request exceeds every candidate
 * (i.e. the source's native resolution is the ceiling). */
function pickNearestWidth(widths: number[], target: number): number {
  const sorted = [...widths].sort((a, b) => a - b);
  const atLeast = sorted.find((candidate) => candidate >= target);
  return atLeast ?? sorted[sorted.length - 1]!;
}

/**
 * Static-export-safe next/image loader. Every candidate width next/image
 * asks for is resolved against the build-time manifest generated by
 * scripts/optimize-images.mjs — the nearest available generated width is
 * used (never assumed to exist exactly), and any src missing from the
 * manifest falls back to the original asset instead of producing a broken
 * URL, so a missing prebuild step degrades gracefully rather than crashing.
 */
export default function imageLoader({ src, width }: ImageLoaderProps): string {
  const entry = IMAGE_MANIFEST[src];

  if (!entry || entry.widths.length === 0) {
    return `${BASE_PATH}${src}`;
  }

  const chosenWidth = pickNearestWidth(entry.widths, width);
  const slug = slugify(src);
  return `${BASE_PATH}/${OPTIMIZED_DIR}/${slug}-${chosenWidth}.webp`;
}
